####
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username":"Eric",
    "email":"Eric@gmail.com",
    "password":"EricAndres123",
    "role":"user",
    "first_name":"EricProfile",
    "last_name":"FariñaProfile"
}

#### ARTICLE
POST http://localhost:4000/api/article
Content-Type: application/json

{
    "title":"mercadería 1",
    "content":"ete e un objeto de mercaderiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "excerpt":"no se",
    "user_id":1
}




#### ARTICLE
DELETE  http://localhost:4000/api/article/1
Content-Type: application/json

{
    
}