####
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
{
	"username":"Eric",
	"email":"ericfarina@gmail.com",
	"password":"EricFari564",
	"role":"admin",
	"first_name":"First Name",
	"last_name":"Last Name",
	"biography":"A biography",
	"avatar_url":"aaa",
	"birth_date":"2007-02-18"
}
}

#### ARTICLE
POST http://localhost:4000/api/article
Content-Type: application/json

{
    "title":"mercadería 1",
    "content":"ete e un objeto de mercaderiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "excerpt":"no se",
    "user_id":1
}




#### ARTICLE
DELETE  http://localhost:4000/api/user/1
Content-Type: application/json

{
    
}